# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PinCodeSafety' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinCodeSafety
pod 'SwiftInterview'

  target 'PinCodeSafetyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PinCodeSafetyUITests' do
    # Pods for testing
  end

end
